// src/pages/posts/index.jsx
import React from "react";
import path from "path";
import { graphql } from "gatsby";
import Container from "../../components/Container";
import Head from "../../components/Head";
import List from "../../components/List";
import ListItem from "../../components/ListItem";
import Navigation from "../../components/Navigation";
import PageTitle from "../../components/PageTitle";

const links = [
  { title: "Top", path: "/" }
];

export default ({ data }) => (
  <Container>
    <Head
      title="Naoto Kaneko's posts"
      description="Naoto Kaneko's posts"
      url={`${data.site.siteMetadata.rootURL}/posts/`}
      imageURL={`${data.site.siteMetadata.rootURL}/icons/256x256.png`}
    />

    <PageTitle>Posts</PageTitle>
    <List>
      {data.allMarkdownRemark.edges.map(({ node }, index) => (
        <ListItem
          key={index}
          title={node.frontmatter.title}
          href={`/posts/${path.basename(node.fileAbsolutePath, ".md")}.html`}
          tags={node.frontmatter.tags || []} />
      ))}
    </List>
    <Navigation links={links} />
  </Container>
);

export const query = graphql`
  query PostsQuery {
    site {
      siteMetadata {
        rootURL
      }
    }
    allMarkdownRemark(sort: { fields: [frontmatter___time], order: DESC }) {
      edges {
        node {
          frontmatter {
            title
            tags
          }
          fileAbsolutePath
        }
      }
    }
  }
`;

// pages/posts/index.vue
<template>
  <div>
    <page-title>Posts</page-title>
    <ul>
      <li v-for="(post, index) in posts" v-bind:key="index">
        <nuxt-link v-bind:to="post.id + '.html'">{{ post.frontMatter.title }}</nuxt-link>
        <tag-label v-for="(tag, index) in post.frontMatter.tags" :key="index" :name="tag" />
      </li>
    </ul>
    <p class="navigation-links">
      <nuxt-link to="/">Top</nuxt-link>
    </p>
  </div>
</template>

<style scoped>
.navigation-links {
  margin-top: 2rem;
  text-align: center;
}
</style>

<script>
import PageTitle from "~/components/PageTitle.vue";
import TagLabel from "~/components/TagLabel.vue";
import summary from "assets/contents/posts/summary.json";

export default {
  computed: {
    posts() {
      return Object.values(summary).sort((a, b) => Number(b.id) - Number(a.id));
    },
    url() {
      return `${process.env.baseUrl}/posts/`;
    }
  },
  components: {
    PageTitle,
    TagLabel
  },
  head() {
    return {
      title: "Naoto Kaneko's posts",
      meta: [
        { name: "description", content: "Naoto Kaneko's posts" },
        { property: "og:type", content: "blog" },
        { property: "og:title", content: "Naoto Kaneko's posts" },
        { property: "og:description", content: "Naoto Kaneko's posts" },
        { property: "og:url", content: this.url },
        { name: "twitter:title", content: "Naoto Kaneko's posts" },
        { name: "twitter:description", content: "Naoto Kaneko's posts" }
      ],
      link: [{ rel: "canonical", href: this.url }]
    };
  }
};
</script>
