// src/pages/index.jsx
import React from "react";
import { graphql } from "gatsby";
import Link from "gatsby-link";
import Container from "../components/Container";
import Head from "../components/Head";
import List from "../components/List";
import PageTitle from "../components/PageTitle";

export default ({ data }) => (
  <Container>
    <Head
      title="Naoto Kaneko"
      description="Naoto Kaneko's homepage"
      url={data.site.siteMetadata.rootURL}
      imageURL={`${data.site.siteMetadata.rootURL}/icons/256x256.png`}
    />

    <PageTitle>Naoto Kaneko</PageTitle>
    <List>
      <li><Link to="/posts/">Posts</Link></li>
      <li><a href="https://github.com/naoty">GitHub</a></li>
      <li><a href="https://twitter.com/naoty_k">Twitter</a></li>
      <li><a href="https://atcoder.jp/users/naoty">AtCoder</a></li>
    </List>
  </Container>
);

export const query = graphql`
  query TopQuery {
    site {
      siteMetadata {
        rootURL
      }
    }
  }
`;

// pages/index.vue
<template>
  <div>
    <page-title>Naoto Kaneko</page-title>
    <ul>
      <li>
        <nuxt-link to="/posts/">Posts</nuxt-link>
      </li>
      <li>
        <a href="https://github.com/naoty">GitHub</a>
      </li>
      <li>
        <a href="https://twitter.com/naoty_k">Twitter</a>
      </li>
      <li>
        <a href="https://atcoder.jp/users/naoty">AtCoder</a>
      </li>
    </ul>
  </div>
</template>

<script>
import PageTitle from "~/components/PageTitle.vue";

export default {
  components: {
    PageTitle
  },
  head() {
    return {
      title: "Naoto Kaneko",
      meta: [
        { name: "description", content: "Naoto Kaneko's homepage" },
        { property: "og:type", content: "profile" },
        { property: "og:title", content: "Naoto Kaneko" },
        { property: "og:description", content: "Naoto Kaneko's homepage" },
        { property: "og:url", content: process.env.baseUrl },
        { name: "twitter:title", content: "Naoto Kaneko" },
        { name: "twitter:description", content: "Naoto Kaneko's homepage" }
      ],
      link: [{ rel: "canoical", href: process.env.baseUrl }]
    };
  }
};
</script>
